# Generated by Django 5.0.12 on 2025-03-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChilledWaterSettings',
            new_name='ChilledWaterSetting',
        ),
        migrations.RenameModel(
            old_name='EnergyResults',
            new_name='EnergyResult',
        ),
    ]
