# Generated by Django 5.0.12 on 2025-03-12 16:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0002_rename_chilledwatersettings_chilledwatersetting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyresult',
            name='E_pump_cw_calc',
        ),
        migrations.AddField(
            model_name='energyresult',
            name='E_pump_cw_calc_kWh',
            field=models.FloatField(blank=True, editable=False, help_text='Condenser water pumps calculation', null=True),
        ),
        migrations.AddField(
            model_name='energyresult',
            name='PUE_calc_input',
            field=models.FloatField(blank=True, editable=False, help_text='calculated based on E_DC_input_kWh and E_IT_input_kWh', null=True),
        ),
        migrations.AlterField(
            model_name='chilledwatersetting',
            name='cp_water_kJkg_1K',
            field=models.FloatField(blank=True, editable=False, help_text='Index matched to the reference table', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chiller',
            name='chiller_average_power_kW',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chiller',
            name='total_chilled_water_load_kW_thermal',
            field=models.FloatField(blank=True, editable=False, help_text='Excludes TX room as assumed has natural ventilation', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chwpump',
            name='chilled_water_flow_kgs',
            field=models.FloatField(blank=True, editable=False, help_text='Actual flow calc using load and Q = m cp dT', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chwpump',
            name='chilled_water_flow_per_pump_kgs',
            field=models.FloatField(blank=True, editable=False, help_text='Divided by number of pumps operating', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chwpump',
            name='chilled_water_load_kW',
            field=models.FloatField(blank=True, editable=False, help_text='Sum of IT, CRAH fans, lighting, and UPS cooling', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chwpump',
            name='pump_power_kW',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chwpump',
            name='pump_rated_power_kW',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chwpump',
            name='pump_speed_percent',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chwpump',
            name='pump_speed_un_limited_percent',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='chwpump',
            name='volume_flow_m3s',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='crah',
            name='average_fan_power_kW',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='crah',
            name='average_fan_speed_percent',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='crah',
            name='maximum_total_CRAH_airflow_m3s',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='crah',
            name='quantity_for_N_redundancy',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='crah',
            name='quantity_installed_estimate',
            field=models.IntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='crah',
            name='quantity_installed_used',
            field=models.IntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='crah',
            name='redundancy_factor',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='crah',
            name='required_airflow_m3s',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='crah',
            name='total_fan_power_kW',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_CRAC_calc_kWh',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_CRAH_calc_kWh',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_DC_calc_kWh',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_DC_input_kWh',
            field=models.FloatField(help_text='The annual energy usage of the datacenter in kWh'),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_Dehum_InRoom_kWh',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_Humidifier_InRoom_kWh',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_IT_input_kWh',
            field=models.FloatField(help_text='The annual energy usage of the IT equipment in kWh'),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_MAU_calc_kWh',
            field=models.FloatField(blank=True, editable=False, help_text='MAU may or may not include hum and dehum', null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_TX_calc_kWh',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_UPS_calc_kWh',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_cable_losses_calc_kWh',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_chiller_calc_kWh',
            field=models.FloatField(blank=True, editable=False, help_text='Only calculated if the system includes chillers', null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_cooling_tower_calc_kWh',
            field=models.FloatField(blank=True, editable=False, help_text='Only calculated when CTs are present', null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_generator_heating_calc_kWh',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_lighting_calc_kWh',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_pump_chw_primary_calc_kWh',
            field=models.FloatField(blank=True, editable=False, help_text='Only calculated if chilled water is present', null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_pump_chw_secondary_calc_kWh',
            field=models.FloatField(blank=True, editable=False, help_text='Only calculated if chilled water is present', null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_un_accounted_calc_kWh',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='PUE_calc',
            field=models.FloatField(blank=True, editable=False, help_text='Calculated based on E_IT_input_kWh and the calculated E_DC value. This is partial PUE if any subcomponent isn´t yet calculated', null=True),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='TX_total_loss_factor_percent',
            field=models.FloatField(blank=True, editable=False, help_text='= k (Core Loss %) + (Load loss %) x (Actual Load kW / Rated Load kW)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='TX_total_loss_kW',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ups',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UPS_System', to='energy_model.project'),
        ),
    ]
