# Generated by Django 5.0.12 on 2025-03-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0003_remove_energyresult_e_pump_cw_calc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyresult',
            name='E_DC_input_kWh',
            field=models.FloatField(blank=True, help_text='The annual energy usage of the datacenter in kWh', null=True),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_IT_input_kWh',
            field=models.FloatField(blank=True, help_text='The annual energy usage of the IT equipment in kWh', null=True),
        ),
    ]
