# Generated by Django 5.0.12 on 2025-03-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0004_alter_energyresult_e_dc_input_kwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighting',
            name='lighting_controls',
            field=models.CharField(choices=[('On_247', 'On 24/7'), ('Motion_Sensors', 'Motion Sensors'), ('Input_Hours', 'Input Hours Per Day')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='lighting_type',
            field=models.CharField(choices=[('Fluorescent_Tubes', 'Fluorescent Tubes'), ('LED', 'LED')], max_length=100),
        ),
    ]
