# Generated by Django 5.0.12 on 2025-03-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0005_alter_lighting_lighting_controls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighting',
            name='lighting_type',
            field=models.CharField(choices=[('Fluorescent', 'Fluorescent'), ('LED', 'LED')], max_length=100),
        ),
    ]
