# Generated by Django 5.0.12 on 2025-03-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0006_alter_lighting_lighting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighting',
            name='lighting_type',
            field=models.CharField(help_text='Select the type of lighting from the dropdown to determine the lighting load', max_length=100),
        ),
    ]
