# Generated by Django 5.0.12 on 2025-03-12 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0008_alter_lighting_lighting_load_wm2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lighting',
            name='lighting_load_input_Wm2',
            field=models.FloatField(blank=True, help_text='Input the lighting load in W/m2 to override the default value', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='lighting_load_Wm2',
            field=models.FloatField(blank=True, editable=False, help_text='Look up table based on type of lighting', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
