# Generated by Django 5.0.12 on 2025-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0009_lighting_lighting_load_input_wm2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyresult',
            name='E_CRAC_calc_kWh',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_CRAH_calc_kWh',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_Dehum_InRoom_kWh',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_Humidifier_InRoom_kWh',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_MAU_calc_kWh',
            field=models.FloatField(default=0, editable=False, help_text='MAU may or may not include hum and dehum'),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_TX_calc_kWh',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_UPS_calc_kWh',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_cable_losses_calc_kWh',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_chiller_calc_kWh',
            field=models.FloatField(default=0, editable=False, help_text='Only calculated if the system includes chillers'),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_cooling_tower_calc_kWh',
            field=models.FloatField(default=0, editable=False, help_text='Only calculated when CTs are present'),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_generator_heating_calc_kWh',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_lighting_calc_kWh',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_pump_chw_primary_calc_kWh',
            field=models.FloatField(default=0, editable=False, help_text='Only calculated if chilled water is present'),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_pump_chw_secondary_calc_kWh',
            field=models.FloatField(default=0, editable=False, help_text='Only calculated if chilled water is present'),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_pump_cw_calc_kWh',
            field=models.FloatField(default=0, editable=False, help_text='Condenser water pumps calculation'),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_un_accounted_calc_kWh',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
