# Generated by Django 5.0.12 on 2025-03-13 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0010_alter_energyresult_e_crac_calc_kwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighting',
            name='lighting_controls',
            field=models.CharField(help_text='Select the type of lighting control to determine hours per year', max_length=100),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='on_for_hoursyear',
            field=models.FloatField(blank=True, help_text='Hours per year the lighting is on. If provided, this overrides the default value from lighting controls.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
