# Generated by Django 5.0.12 on 2025-03-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0011_alter_lighting_lighting_controls_and_more'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyresult',
            name='E_DC_input_kWh',
            field=models.FloatField(default=0, help_text='The annual energy usage of the datacenter in kWh'),
        ),
        migrations.AlterField(
            model_name='energyresult',
            name='E_IT_input_kWh',
            field=models.FloatField(default=0, help_text='The annual energy usage of the IT equipment in kWh'),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='lighting_controls',
            field=models.ForeignKey(help_text='Select the type of lighting control to determine hours per year', on_delete=django.db.models.deletion.PROTECT, to='equipment.lightingcontrolspecs'),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='lighting_type',
            field=models.ForeignKey(help_text='Select the type of lighting to determine the lighting load', on_delete=django.db.models.deletion.PROTECT, to='equipment.lightingspecs'),
        ),
    ]
