# Generated by Django 5.0.12 on 2025-03-13 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0012_alter_energyresult_e_dc_input_kwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahall',
            name='design_IT_load_kW',
            field=models.FloatField(default=0, help_text='If not provided, will be estimated based on area and load density or installed UPS capacity', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
