# Generated by Django 5.0.12 on 2025-03-14 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0013_alter_datahall_design_it_load_kw'),
    ]

    operations = [
        migrations.AddField(
            model_name='lighting',
            name='on_for_hoursyear_input',
            field=models.FloatField(blank=True, help_text='Hours per year the lighting is on. If provided, this overrides the default value from lighting controls.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='on_for_hoursyear',
            field=models.FloatField(default=0, editable=False, help_text='Infered from lighting controls', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
