# Generated by Django 5.0.12 on 2025-03-14 10:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0014_lighting_on_for_hoursyear_input_and_more'),
        ('equipment', '0004_merge_20250314_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformer',
            name='core_loss_factor_percent_input',
            field=models.FloatField(blank=True, help_text='Input core loss factor to override the default value', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='transformer',
            name='load_loss_factor_percent_input',
            field=models.FloatField(blank=True, help_text='Input load loss factor to override the default value', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='core_loss_factor_percent',
            field=models.FloatField(blank=True, editable=False, help_text='Core loss factor from specs or manual input', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='load_loss_factor_percent',
            field=models.FloatField(blank=True, editable=False, help_text='Load loss factor from specs or manual input', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='transformer_type',
            field=models.ForeignKey(help_text='Select the type of transformer to determine default loss factors', on_delete=django.db.models.deletion.PROTECT, to='equipment.transformerspecs'),
        ),
    ]
