# Generated by Django 5.0.12 on 2025-03-14 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_model', '0016_alter_transformer_e_dc_power_kw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformer',
            name='E_DC_power_kW',
            field=models.FloatField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='TX_total_loss_factor_percent',
            field=models.FloatField(blank=True, default=0, editable=False, help_text='= k (Core Loss %) + (Load loss %) x (Actual Load kW / Rated Load kW)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='TX_total_loss_kW',
            field=models.FloatField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='average_utilization',
            field=models.FloatField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='total_installed_capacity_kW',
            field=models.FloatField(default=0, editable=False, help_text='Including redundancy', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
