# Generated by Django 5.0.12 on 2025-03-13 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightingControlSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type', models.CharField(max_length=100)),
                ('hours_per_year', models.FloatField(default=0, help_text='Number of hours per year the lighting is on', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8760)])),
            ],
            options={
                'verbose_name': 'Lighting Control Specification',
                'verbose_name_plural': 'Lighting Control Specifications',
            },
        ),
        migrations.CreateModel(
            name='LightingSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting_type', models.CharField(max_length=100)),
                ('lighting_load_Wm2', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
