# Generated by Django 5.0.12 on 2025-03-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_transformerspecs'),
        ('equipment', '0003_populate_transformer_specs'),
    ]

    operations = [
    ]
